# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jS2T29qxiFPvfLqdKzz2YkpwOv9mEY6z/dNwLvIrHNNjlhNhhjSj0KcyoBWNwNqqYnixKIBImaJP68z9Y8R+E+9ozGIUgK21aGWFUEsGp/IiqatTeal2Bkj4GD6+OOoxukZRB3THR9BZ1eSH4f2YfvcAcUGbRgiB1kxja5hOgHh/w/CX2bQJDeWYVxoUq4dekjcR2wGdbqMGvBtf86LTOwJ6TGOfMxmoFa9+P9/7VjAxZfb8kHOIahWJxeVGERvfNj88u8DzLoR50kT2u6KxxhH7dzGnTgN4cXkQMRjqMMyXPHsFRKOeS5I65ipqNGj5sfg2UFmTAh+oiyBGDD5D8rAaIssJb+iv4KNEumYA9CewAD85R/jQoGWt3lqIM1tUMYh0S5If4UUvJt6Vjth/wFI9oSeOmMo43oDUeavDNjVC2HlB49vmxvxhq5Tm7I0neHPp/XNwseqKMTk6F6yqdf2dvk+ByAsjHYcnlYVSti6dpgiwn1fGhefBfqTr+ahGq9HWWB2t18WjO0tQZB+Dl1yhwfYrVrv5Xqjyri07HA0kifQqJcECET6wOshfOlXLtkzqciDuQXBFPDFWSZqKglcn4YYWHtGrMjOe3KIt6K4WhjOnkh56mD1ddZCnzq5+OQgyV/MLetdcGtqve0Uux94zGcHXTaDnCGnm84RmCsM="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
