travis:
  secure:
    BINSTAR_TOKEN: jS2T29qxiFPvfLqdKzz2YkpwOv9mEY6z/dNwLvIrHNNjlhNhhjSj0KcyoBWNwNqqYnixKIBImaJP68z9Y8R+E+9ozGIUgK21aGWFUEsGp/IiqatTeal2Bkj4GD6+OOoxukZRB3THR9BZ1eSH4f2YfvcAcUGbRgiB1kxja5hOgHh/w/CX2bQJDeWYVxoUq4dekjcR2wGdbqMGvBtf86LTOwJ6TGOfMxmoFa9+P9/7VjAxZfb8kHOIahWJxeVGERvfNj88u8DzLoR50kT2u6KxxhH7dzGnTgN4cXkQMRjqMMyXPHsFRKOeS5I65ipqNGj5sfg2UFmTAh+oiyBGDD5D8rAaIssJb+iv4KNEumYA9CewAD85R/jQoGWt3lqIM1tUMYh0S5If4UUvJt6Vjth/wFI9oSeOmMo43oDUeavDNjVC2HlB49vmxvxhq5Tm7I0neHPp/XNwseqKMTk6F6yqdf2dvk+ByAsjHYcnlYVSti6dpgiwn1fGhefBfqTr+ahGq9HWWB2t18WjO0tQZB+Dl1yhwfYrVrv5Xqjyri07HA0kifQqJcECET6wOshfOlXLtkzqciDuQXBFPDFWSZqKglcn4YYWHtGrMjOe3KIt6K4WhjOnkh56mD1ddZCnzq5+OQgyV/MLetdcGtqve0Uux94zGcHXTaDnCGnm84RmCsM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
