travis:
  secure:
    BINSTAR_TOKEN: X8p6zt8slXtAT4fs3GZO3FxN9tSxdBrMNT2Aecppb1lRdtNvfjUWqjJDJUWZ3eqkYbj42YuFBZ3ZqpQPdALLobtHlcrZKOOMo6u2G44CgecoJU6829KIl6otAgVdkVSSKmjQZ/4OcaYHXSlQIuxB+cvsjvler98pU9M8942EdOx9wF8V7SmZkoRinlmY/wmxd8mGeSByeN+dQP2TIgvoeNTG0Ni23TQbHxEvWTSAtu+IwqZYJZrbHsU3+d2LsYOrqkYdwpMrIn5Xl2cEu3JFiRHeKC8UfCjL6+2/s48ONqCHLIGAUiuW2jD3gJQfp92FqRuZZHaxQCbU8stJCJdjFsygv9MCMpga/zjgRCaJXRjsetzbA2NoVJpYF235B46RP1VrBMt7b1dRvXv0kWtMQcOABuDQdfx+VeDw7tfatjZy+Slvrd1Wv5V1Hs4GFXe8FhjM0DCa+7tPwQMFt3UGgovxz/eobi5rxDjOHsIx1jStPa13B6opbd86EHg0bknxqpgFYziCnbbFSeetwd3Xbk4kxNog4E5ETINbUXWBuRbJo90h0s5Mg94zdA4EtdmQbRNk0ZQ55uRvTvlD1xR3ibjCLiquuoPd78Mhx1kSoP3NcE74jOPeAB/HQAoTL3LPkvTbSUFxCwqEliAp4h+ZJ1jLuReFBBzsc4NSxgodd5k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
